language: php

php:
  - 7.1
  - 7.2
  - 7.3

env:
  - LARAVEL_VERSION=5.8

before_install:
  - composer self-update >/dev/null 2>&1
  - composer require laravel/framework:${LARAVEL_VERSION} --no-update

install: composer update --prefer-source --no-interaction

script: vendor/bin/phpunit --coverage-clover ./tests/logs/clover.xml

after_script:
- php vendor/bin/coveralls -v

branches:
  only:
  - staging
  - stable

notifications:
  email:
  - hello@hisorange.me

# Thanks for this awesome service @TravisCI!